name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # Removing the cache option which is causing problems
      
      - name: Debug - List Files
        run: |
          ls -la
          find . -name "package.json" | xargs dirname
      
      - name: Install dependencies
        run: |
          cd $(find . -name "package.json" | xargs dirname | head -n 1)
          npm install
      
      - name: Build
        run: |
          cd $(find . -name "package.json" | xargs dirname | head -n 1)
          npm run build
      
      - name: List build directory
        run: |
          cd $(find . -name "package.json" | xargs dirname | head -n 1)
          ls -la dist || echo "No dist directory found"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './$(find . -name "package.json" | xargs dirname | head -n 1)/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2